version: '3'
services:
  docker-bot:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 20s
      resources:
        limits:
          cpus: 2
          memory: 200M
        reservations:
        cpus: 2
        memory: 100M
      depends_on:
        - redis

  redis:
    image: redis
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.db == yes
      resources:
        limits:
          cpus: "1"
          memory: "500M"
        reservations:
          cpus: "1"
          memory: "200M"